language: c

compiler:
  - gcc
  - clang

dist: bionic
sudo: false

addons:
  apt:
    packages:
      - astyle
      - libcunit1-dev
      - libaio-dev
      - libssl-dev
      - libnuma-dev
      - uuid-dev

before_script:
  - git submodule update --init
  # temporarily disable shellcheck which gives errors in upstream
  - sudo rm `which shellcheck`
  - export MAKEFLAGS="-j$(nproc)"

script:
  - ./scripts/check_format.sh
  - ./configure --enable-werror --without-isal --enable-debug
  - make
  - ./test/unit/unittest.sh
